/**
 * Two jobs:
 *   1. Convert icons/icon.svg into PNG files at the sizes required by the
 *      extension (48 / 96 / 128 — matched by manifest.json's icons block).
 *   2. Extract a small subset of FontAwesome Free Solid SVG path data into
 *      lib/fa-icons.js so content scripts can render those glyphs as
 *      inline SVG. Inline SVG sidesteps the FA version mismatch across
 *      target pages: Treeherder ships no FA font, Phab ships FA 4.7.0
 *      (which lacks plane-arrival, fast-backward, etc.), and Bugzilla
 *      ships FA 5 Free Solid.
 *
 * Run after changing the SVG source or bumping the FA dep:
 *     npm run generate-icons
 */
import { Resvg } from "@resvg/resvg-js";
import { readFileSync, writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const dir = dirname(fileURLToPath(import.meta.url));

// --- 1. Extension PNG icons -----------------------------------------------
const svg = readFileSync(join(dir, "icons", "icon.svg"));
for (const size of [48, 96, 128]) {
  const resvg = new Resvg(svg, { fitTo: { mode: "width", value: size } });
  const png = resvg.render().asPng();
  const out = join(dir, "icons", `icon-${size}.png`);
  writeFileSync(out, png);
  console.log(`wrote ${out}`);
}

// --- 2. FontAwesome Free path data → lib/fa-icons.js -----------------------
// Each entry: { viewBox, path } — extracted verbatim from FA Free Solid.
// Hardcoded map of icon name → literal SVG filename. Each path is a
// string literal so there is no dynamic path construction and no path-
// traversal risk. Add new icons here; bump the FA dep and re-run to
// regenerate lib/fa-icons.js with the updated paths.
const FA_DIR = join(dir, "node_modules/@fortawesome/fontawesome-free/svgs/solid");
const FA_ICON_FILES = {
  "plane-arrival": join(FA_DIR, "plane-arrival.svg"),
  "fast-backward": join(FA_DIR, "fast-backward.svg"),
  clone: join(FA_DIR, "clone.svg"),
  "circle-check": join(FA_DIR, "circle-check.svg"),
};

// SVG path commands + numeric literals only — sanity check that an FA dep
// bump hasn't shipped a `d="…"` attribute containing anything we'd splice
// straight into a setAttribute call without parsing.
const VALID_PATH_RE = /^[MmLlHhVvCcSsQqTtAaZz0-9\s,.\-+eE]*$/;

const extractSvg = (src) => {
  const viewBox = src.match(/viewBox="([^"]+)"/)?.[1];
  const path = src.match(/<path[^>]*\bd="([^"]+)"/)?.[1];
  if (!viewBox || !path) throw new Error("Failed to parse FA SVG");
  if (!VALID_PATH_RE.test(path))
    throw new Error(`FA SVG path contains unexpected characters: ${path.slice(0, 80)}…`);
  return { viewBox, path };
};

const entries = Object.entries(FA_ICON_FILES).map(([name, filepath]) => [
  name,
  extractSvg(readFileSync(filepath, "utf8")),
]);

const body = entries
  .map(
    ([name, { viewBox, path }]) =>
      `  ${JSON.stringify(name)}: { viewBox: ${JSON.stringify(viewBox)}, path: ${JSON.stringify(path)} },`,
  )
  .join("\n");

const faOut = `// AUTO-GENERATED by generate-icons.mjs from @fortawesome/fontawesome-free.
// Do not edit by hand. Run \`npm run generate-icons\` to regenerate.
//
// Path data licensed under CC BY 4.0 by Font Awesome
// (https://fontawesome.com/license/free).

const FA_ICONS = {
${body}
};

if (typeof module !== "undefined" && module.exports) module.exports = { FA_ICONS };
`;

const faOutPath = join(dir, "lib", "fa-icons.js");
writeFileSync(faOutPath, faOut);
console.log(`wrote ${faOutPath}`);
